extends Node

signal view_changed(previous_view_id: ViewIds.Id, next_view_id: ViewIds.Id)
signal debug_mode_changed(enabled: bool)
signal game_time_pause_changed(paused: bool)
signal grid_cell_changed(view_id: ViewIds.Id, coord: GridCoord, cell: CellData)
signal grid_loaded()
signal grid_saved()
signal grid_hover_changed(coord: GridCoord, cell: CellData)
signal game_mode_changed(previous_mode: int, next_mode: int)
signal resolution_changed(preset: ResolutionPresets.Id)
signal build_blocked(coord: GridCoord, reason: String)
signal day_period_changed(previous_period: int, next_period: int)
signal view_theme_changed(view_id: ViewIds.Id, theme_id: String)
signal furniture_placed(instance: FurnitureInstance)
signal furniture_removed(instance: FurnitureInstance)
signal furniture_placement_blocked(origin: GridCoord, reason: String)
signal furniture_catalog_changed()
signal furniture_loaded()
signal navigation_rebuilt(view_id: ViewIds.Id)
signal navigation_map_ready(view_id: ViewIds.Id)
signal entity_spawned(unit: UnitEntity)
signal entity_selected(unit: UnitEntity)
signal entity_move_command(entity_id: String, target_position: Vector2)
signal morning_briefing_requested(day: int)
signal day_started(day: int)
signal day_ended(day: int, summary: Dictionary)
signal day_settled(summary: Dictionary)
signal economy_changed()
signal reputation_changed()
signal customer_spawned(customer: CustomerEntity)
signal customer_selected(customer: CustomerEntity)
signal customer_reviewed(customer: CustomerEntity, rating: float, comment: String)
signal game_over(reason: String)
signal game_hour_changed(hour: float)
signal staff_task_changed(task: int)
